# Generated by Django 2.0.6 on 2018-07-13 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('in_wishlist', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EquipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_name', models.CharField(max_length=200)),
                ('price_per_head', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('no_in_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='attr',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equips.EquipInfo'),
        ),
    ]
