# Generated by Django 2.0.6 on 2018-07-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipinfo',
            name='equip_dept',
            field=models.CharField(default='physics', max_length=200),
            preserve_default=False,
        ),
    ]
